
<?php
/**
 * Product list template
 *
 * @var $block \KonsolStudio\Test\Block\Product\View\Configurable
 */
use Magento\Framework\App\Action\Action;
?>
<?php
$_product = $block->getConfigurableProduct();
$currentOptions = $block->getCurrentOptions();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$image = 'category_page_list';
$showDescription = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
$listBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
?>
<?php if($_product): ?>
    <div class="product-item-info" data-container="product-list">
        <?php
        $productImage = $block->getImage($_product, $image);
        $position = ' style="left:' . $productImage->getWidth() . 'px;'
            . 'top:' . $productImage->getHeight() . 'px;"';
        ?>
        <?php // Product Image ?>
        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
            <?= $productImage->toHtml() ?>
        </a>
        <div class="product details product-item-details">
            <?php
            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
            ?>
            <strong class="product name product-item-name">
                <a class="product-item-link"
                   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                </a>
            </strong>
            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
            <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
            <?= $block->getProductDetailsHtml($_product) ?>

            <div class="product-item-inner">
                <div class="product actions product-item-actions">
                    <div class="actions-primary">
                        <?php if ($_product->isSaleable()): ?>
                            <?php $postParams = $listBlock->getAddToCartPostParams($_product); ?>
                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                <?= $block->getBlockHtml('formkey') ?>
                                <button type="submit"
                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                        class="action tocart primary">
                                    <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                </button>
                            </form>
                        <?php else: ?>
                            <?php if ($_product->isAvailable()): ?>
                                <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                            <?php else: ?>
                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                </div>
                <?php if ($showDescription):?>
                    <div class="product description product-item-description">
                        <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                           class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endif; ?>